# Generated by Django 2.2.2 on 2019-06-07 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20190606_0945'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event_channel',
            unique_together={('channel', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'event')},
        ),
    ]
