# Generated by Django 2.2.2 on 2019-06-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190607_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='event_channel',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='image',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='participation',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
